### ISSUE TITLE
R CMD checks with devel version of tidyr

### ISSUE THREAD

**Issue by hadley** [Molmed/emil#2]
```
checking whether package ‘emil’ can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import by ‘tidyr::%>%’ when loading ‘emil’
See ‘/private/tmp/Rtmp5nYH93/check_cranb673158d7feb/emil.Rcheck/00install.out’ for details.
```

probably because you're doing too many unqualified imports

**Comment by backlin** [comment]
I have changed all uses of @import to @importFrom to avoid future problems of this kind. To avoid importing (and attaching) the entire **dplyr** package, I now import only the functions I need and re-export `dplyr::select`, rather than having **dplyr** as a dependency.

Suggested packages are still loaded at runtime using `requireNamespace` and their functions are accessed with `::`. I believe this should be safe but please correct me if there is a better way to do it.

Thanks for taking your time to check my package!

**Comment by hadley** [comment]
Looks good!
